### ISSUE TITLE
Permissions seem to be hard-coded

### ISSUE THREAD

**Issue by powerdude** [mikenye/docker-youtube-dl#10]
Hello,

i have my PGID and PUID set in a docker-compose, but it seems like they are being ignored.  I keep getting errors when the app tries to update the archive file.  here's my compose:

```
  youtube-dl-cron:
    image: mikenye/youtube-dl:latest
    container_name: youtube-dl-cron
    # need compose v2 cpus: 1
    restart: "no"
    volumes:
      #- ${CONFIG_DIR}/youtube-dl-server/data:/youtube-dl
      - ${VIDEOS}/youtube:/workdir
      - ${CONFIG_DIR}/youtube/youtube-dl.conf:/etc/youtube-dl.conf:ro
      - ${CONFIG_DIR}/youtube/.youtube-dl-archive:/etc/.youtube-dl-archive
      - ${CONFIG_DIR}/youtube/.cache:/etc/.cache
      - ${CONFIG_DIR}/youtube/.youtube-dl-cookiejar:/etc/.youtube-dl-cookiejar
      - ${CONFIG_DIR}/youtube/channels.txt:/etc/channels.txt
      - ${CONFIG_DIR}/youtube/.netrc:/home/dockeruser/.netrc:ro
    environment:
      - PUID: 1024
      - PGID: 100
      - TZ: $TZ
      - LC_ALL=C.UTF-8
```

and here's the perms of my files:

```
drwxrwxr-x   4 synoadmin users  4096 Aug 17 00:49 ./
drwxrwxr-x 100 synoadmin users  4096 Aug  5 19:51 ../
drwxrwxr-x   3 synoadmin users  4096 Aug 17 22:05 .cache/
-rw-rw-r--   1 synoadmin users  2677 Sep  5 21:20 channels.txt
drwxrwxr-x   2 synoadmin users  4096 Jul 12 16:40 logs/
-rw-rw-r--   1 synoadmin users    90 Jul 12 16:40 .netrc
-rw-rw-r--   1 synoadmin users 32280 Sep 11 21:39 .youtube-dl-archive
-rw-rw-r--   1 synoadmin users  1130 Sep  5 19:47 youtube-dl.conf
-rw-rw-r--   1 synoadmin users   584 Sep  8 00:03 .youtube-dl-cookiejar
-rw-rw-r--   1 synoadmin users   331 Aug 17 00:35 youtube.sh
```

synoadmin=1024 and users=100.  And here are the errors i'm getting:

```
ERROR: [Errno 13] Permission denied: '/etc/.youtube-dl-archive'
today at 9:48 PM Traceback (most recent call last):
today at 9:48 PM File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 808, in extract_info
today at 9:48 PM return self.process_ie_result(ie_result, download, extra_info)
today at 9:48 PM File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 863, in process_ie_result
today at 9:48 PM return self.process_video_result(ie_result, download=download)
today at 9:48 PM File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1644, in process_video_result
today at 9:48 PM self.process_info(new_info)
today at 9:48 PM File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2004, in process_info
today at 9:48 PM self.record_download_archive(info_dict)
today at 9:48 PM File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2121, in record_download_archive
today at 9:48 PM with locked_file(fn, 'a', encoding='utf-8') as archive_file:
today at 9:48 PM File "/usr/local/bin/youtube-dl/youtube_dl/utils.py", line 3279, in __init__
today at 9:48 PM self.f = io.open(filename, mode, encoding=encoding)
today at 9:48 PM IOError: [Errno 13] Permission denied: '/etc/.youtube-dl-archive'
```

Am i doing something wrong or do i have to use 1000:1000.  Note, i may have previously chown to this before, but i'm restoring from a backup and now running into this issue and would prefer not to change just this folder again.

thanks
