### ISSUE TITLE
YTDL Command Line Assistance + Locales

### ISSUE THREAD

**Issue by powerdude** [mikenye/docker-youtube-dl#7]
Sorry to open an issue, but i have a question about performance but I don't know if it is a YTDL or this container.  When i run this with multiple subs and some of the subs may have 1-2K videos, it seems to take 9 hours for this container to run as it always starts at video 1 to see if the video meets the date criteria?  Is there a way for this to start at the last video and stop sooner?

**Comment by mikenye** [comment]
Hi @powerdude can you share your `docker run` syntax with all of the arguments you are passing to `youtube-dl`?

**Comment by mikenye** [comment]
Could you consider using the `--playlist-end` and `--download-archive` arguments?

For example:

```bash
docker run \
    --rm \
    -it \
    --name youtube-dl-cron \
    --cpus 1 \
    -v /tmp/ytdltest:/workdir \
    mikenye/youtube-dl \
    https://www.youtube.com/c/channel/videos \
    --dateafter now-5days \
    --skip-download \
    --download-archive /workdir/archive.txt \
    --playlist-end 20
```

This will start from the most recent video in the playlist/channel, and work backwards for up to 20 videos and/or until you reach videos older than `now-5days`.

Putting a limit on the number of entries in the playlist using `--playlist-end` should hopefully prevent it from checking every video. You may need to adjust this number so you're always getting all the new videos each time you run it.

Using the `--download-archive` should prevent it trying to download videos it has already downloaded.

See if that helps and let me know.

**Comment by powerdude** [comment]
hi @mikenye.  I use `docker-compose` and `ofelia` to trigger the container.  here's my compose:

```
  youtube-dl-cron:
    image: mikenye/youtube-dl:latest
    container_name: youtube-dl-cron
    network_mode: "service:vpn"
    cpus: 1
    restart: "no"
    depends_on:
      - vpn
    volumes:
      #- ${CONFIG_DIR}/youtube-dl-server/data:/youtube-dl
      - ${VIDEOS}/youtube:/workdir
      - ${CONFIG_DIR}/youtube/youtube-dl.conf:/etc/youtube-dl.conf:ro
      - ${CONFIG_DIR}/youtube/.youtube-dl-archive:/etc/.youtube-dl-archive
      - ${CONFIG_DIR}/youtube/.cache:/etc/.cache
      - ${CONFIG_DIR}/youtube/.youtube-dl-cookiejar:/etc/.youtube-dl-cookiejar
      - ${CONFIG_DIR}/youtube/channels.txt:/etc/channels.txt
    environment:
      PUID: 1000
      PGID: 1000
      TZ: $TZ
```

all settings are in the `.conf` file and i was already using the `--download-archive`.  

```
# debug
-v

#--netrc
--cookies /etc/.youtube-dl-cookiejar

--download-archive /etc/.youtube-dl-archive  
--dateafter now-10days  
--cache-dir /etc/.cache
--ignore-errors
--no-overwrites
--continue
--no-post-overwrites
--merge-output-format mp4
--playlist-reverse
--playlist-end 20
--restrict-filenames
--geo-bypass

# get metadata
--write-description
--write-info-json
--write-annotations
--write-thumbnail
--add-metadata

# formatting
--format "(mp4)best[height<=?720]"
--fixup fix
--max-downloads 64
--output '/workdir/%(uploader)s [%(channel_id)s]/%(playlist_index)s - %(title)s [%(id)s].%(ext)s'
--batch-file '/etc/channels.txt'
```

the `--playlist-end` works to limit things, but now the `playlist_index` is now limited to `20` and throws off Plex.
